version: '3.8'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: flaskdb
    volumes:
      - dbData:/var/lib/mysql

  app:
    build:
      context: ./app
    links:
      - "db"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  dbData: {}