version: '3.8'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: flaskdb
    volumes:
      - dbData:/var/lib/mysql

  check-db-readiness: 
    image: jwilder/dockerize:0.6.1
    depends_on:
      - db
    command: 'dockerize -wait tcp://db:3306 -timeout 60m'

  app:
    build:
      context: ./app
    container_name: myapp
    links:
      - db
    ports:
      - "3000:3000"
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3

volumes:
  dbData: {}