version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: flaskdb
    volumes:
      - dbData:/var/lib/mysql

  app:
    build:
      context: ./app
    container_name: myapp
    links:
      - db
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: bash -c "./wait-for-it.sh --timeout=60 --strict db:3306 && python main.py"
    restart: on-failure

  web:
    build:
      context: ./web
    container_name: myweb
    links:
      - app
    depends_on:
      - app
    ports:
      - "80:80"
    restart: on-failure
    
volumes:
  dbData: {}