version: '3.8'
services:
   vprodb:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: flaskdb
    volumes:
      - vprodbdata:/var/lib/mysql

  vproapp:
    build:
      context: ./app
    links:
      - "vprodb"
    ports:
      - "3000:3000"

volumes:
  vprodbdata: {}