- name: Set Up Tasks
  hosts: server_2
  tasks:
    - name: Import Variables for APP Setup
      include_vars: variables.yml

    - name: Installing Python3 on the machine
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - python3
        - python3-pip
      register: package_out

    - name: Clone git repo for source code
      git:
        repo: "{{git_url}}"
        dest: /tmp/flask_python
        version: python_sec
      register: git_out

    - name: Copy Database Connection Configuration file
      template:
        src: vars/config.j2
        dest: /tmp/nodejs/app/database/config.js

    - name: CD into the clonned repository and Install NPM modules
      command: "npm install"
      args:
        chdir: /tmp/nodejs/app
      when: git_out.changed
      register: npm_out

    - name: SetUP systemd configuration file to start the App
      template:
        src: templates/nodejs_svc.j2
        dest: /etc/systemd/system/nodejsapp.service

    - name: Reload the systemd file
      systemd:
        daemon_reload: true

    - name: Start and Enable the nodejsapp using systemd
      systemd:
        name: nodejsapp
        state: started
        enabled: true
      register: sys_out

