- name: Set Up Tasks
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Import Variables for APP Setup
      include_vars: variables.yml

    - name: Installing Python3 on the machine
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - python3
        - python3-pip
      register: package_out

    - name: Clone git repo for source code
      git:
        repo: "{{git_url}}"
        dest: /tmp/flask_python
        version: python_sec
        force: True
      register: git_out

    - name: Copy Database Connection Configuration file
      template:
        src: templates/config.j2
        dest: /tmp/flask_python/python-ansible-stack/pythonapp/files/config.py

    - name: CD into the clonned repository and Install App Dependies
      command: "pip install -r requirements.txt"
      args:
        chdir: /tmp/flask_python/python-ansible-stack/pythonapp/files
      register: pip_out