- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    # - name: Import variables for Security Group Setup
      # include_vars: variables.yml

    - name: Create Security group for Load balancer
      ec2_group:
        name: "{{dbuser}}"
        description: Security Group for the Load balancer
        region: "{{region}}"
        rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
          rule_desc: Allow HTTP from any where
        tags:
          Name: user"
      register: lb_SG_out
