- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create EC2 Key Pair
      ec2_key:
        name: nodejs
        region: us-east-1
      register: keyout

    - name: Store Login Key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./nodejs_key.pem
      when: keyout.changed

    - name: Store Login key name as variable
      blockinfile:
        path: ./vars/variaables.yml
        block: |
          key_name: {{keyout.key.name}}