- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import Variables for VPC Setup
      include_vars: variables.yml

    - name: Copy Database Connection Configuration file
      template:
        src: templates/config.j2
        dest: /tmp/config.js